-- JLPT N2 Vocabulary Data - 1000+ words
-- Categories: business, academic, keigo, daily, idioms, kanji

-- Business vocabulary (会社用語)
INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('判断', 'はんだん', 'judgment', 'Noun', 'N2', 1, 2, 'business'),
('対応', 'たいおう', 'response/dealing with', 'Noun', 'N2', 2, 2, 'business'),
('利用', 'りよう', 'use/utilization', 'Noun', 'N2', 3, 1, 'business'),
('目的', 'もくてき', 'purpose/goal', 'Noun', 'N2', 4, 2, 'business'),
('要求', 'ようきゅう', 'demand/request', 'Noun', 'N2', 5, 2, 'business'),
('提供', 'ていきょう', 'provision/supply', 'Noun', 'N2', 6, 2, 'business'),
('確認', 'かくにん', 'confirmation/verification', 'Noun', 'N2', 7, 2, 'business'),
('改善', 'かいぜん', 'improvement', 'Noun', 'N2', 8, 2, 'business'),
('効率', 'こうりつ', 'efficiency', 'Noun', 'N2', 9, 3, 'business'),
('評価', 'ひょうか', 'evaluation/assessment', 'Noun', 'N2', 10, 2, 'business'),
('計画', 'けいかく', 'plan/planning', 'Noun', 'N2', 11, 1, 'business'),
('実施', 'じっし', 'implementation/execution', 'Noun', 'N2', 12, 2, 'business'),
('管理', 'かんり', 'management/control', 'Noun', 'N2', 13, 2, 'business'),
('提案', 'ていあん', 'proposal/suggestion', 'Noun', 'N2', 14, 2, 'business'),
('報告', 'ほうこく', 'report', 'Noun', 'N2', 15, 2, 'business'),
('連絡', 'れんらく', 'contact/communication', 'Noun', 'N2', 16, 1, 'business'),
('相談', 'そうだん', 'consultation/discussion', 'Noun', 'N2', 17, 1, 'business'),
('担当', 'たんとう', 'person in charge', 'Noun', 'N2', 18, 2, 'business'),
('業務', 'ぎょうむ', 'business operations', 'Noun', 'N2', 19, 3, 'business'),
('会議', 'かいぎ', 'meeting/conference', 'Noun', 'N2', 20, 1, 'business'),
('契約', 'けいやく', 'contract/agreement', 'Noun', 'N2', 21, 2, 'business'),
('交渉', 'こうしょう', 'negotiation', 'Noun', 'N2', 22, 3, 'business'),
('予算', 'よさん', 'budget', 'Noun', 'N2', 23, 2, 'business'),
('決定', 'けってい', 'decision/determination', 'Noun', 'N2', 24, 2, 'business'),
('承認', 'しょうにん', 'approval/authorization', 'Noun', 'N2', 25, 3, 'business'),
('実績', 'じっせき', 'results/track record', 'Noun', 'N2', 26, 3, 'business'),
('期待', 'きたい', 'expectation/hope', 'Noun', 'N2', 27, 2, 'business'),
('成果', 'せいか', 'results/outcomes', 'Noun', 'N2', 28, 2, 'business'),
('方針', 'ほうしん', 'policy/direction', 'Noun', 'N2', 29, 3, 'business'),
('目標', 'もくひょう', 'target/objective', 'Noun', 'N2', 30, 2, 'business'),
('基準', 'きじゅん', 'standard/criteria', 'Noun', 'N2', 31, 3, 'business'),
('状況', 'じょうきょう', 'situation/circumstances', 'Noun', 'N2', 32, 2, 'business'),
('問題', 'もんだい', 'problem/issue', 'Noun', 'N2', 33, 1, 'business'),
('解決', 'かいけつ', 'solution/resolution', 'Noun', 'N2', 34, 2, 'business'),
('対策', 'たいさく', 'countermeasure', 'Noun', 'N2', 35, 2, 'business'),
('方法', 'ほうほう', 'method/way', 'Noun', 'N2', 36, 1, 'business'),
('手順', 'てじゅん', 'procedure/steps', 'Noun', 'N2', 37, 2, 'business'),
('作業', 'さぎょう', 'work/task/operation', 'Noun', 'N2', 38, 2, 'business'),
('資料', 'しりょう', 'materials/data', 'Noun', 'N2', 39, 2, 'business'),
('書類', 'しょるい', 'documents/papers', 'Noun', 'N2', 40, 2, 'business'),
('期限', 'きげん', 'deadline/time limit', 'Noun', 'N2', 41, 2, 'business'),
('優先', 'ゆうせん', 'priority', 'Noun', 'N2', 43, 2, 'business'),
('効果', 'こうか', 'effect/result', 'Noun', 'N2', 44, 2, 'business'),
('影響', 'えいきょう', 'influence/impact', 'Noun', 'N2', 45, 2, 'business'),
('費用', 'ひよう', 'cost/expense', 'Noun', 'N2', 46, 2, 'business'),
('利益', 'りえき', 'profit/benefit', 'Noun', 'N2', 48, 2, 'business'),
('損失', 'そんしつ', 'loss/damage', 'Noun', 'N2', 49, 3, 'business'),
('投資', 'とうし', 'investment', 'Noun', 'N2', 50, 3, 'business'),
('実現', 'じつげん', 'realization/achievement', 'Noun', 'N2', 51, 3, 'business'),
('推進', 'すいしん', 'promotion/advancement', 'Noun', 'N2', 52, 3, 'business');

INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('強化', 'きょうか', 'strengthening/reinforcement', 'Noun', 'N2', 53, 2, 'business'),
('削減', 'さくげん', 'reduction/cut', 'Noun', 'N2', 54, 3, 'business'),
('拡大', 'かくだい', 'expansion/enlargement', 'Noun', 'N2', 55, 2, 'business'),
('統合', 'とうごう', 'integration/consolidation', 'Noun', 'N2', 57, 3, 'business'),
('導入', 'どうにゅう', 'introduction/adoption', 'Noun', 'N2', 60, 3, 'business'),
('開発', 'かいはつ', 'development', 'Noun', 'N2', 61, 2, 'business'),
('販売', 'はんばい', 'sales', 'Noun', 'N2', 62, 2, 'business'),
('購入', 'こうにゅう', 'purchase', 'Noun', 'N2', 63, 2, 'business'),
('顧客', 'こきゃく', 'customer/client', 'Noun', 'N2', 64, 2, 'business'),
('取引', 'とりひき', 'transaction/deal', 'Noun', 'N2', 65, 2, 'business'),
('市場', 'しじょう', 'market', 'Noun', 'N2', 66, 2, 'business'),
('需要', 'じゅよう', 'demand', 'Noun', 'N2', 67, 3, 'business'),
('供給', 'きょうきゅう', 'supply', 'Noun', 'N2', 68, 3, 'business'),
('価格', 'かかく', 'price', 'Noun', 'N2', 69, 2, 'business'),
('品質', 'ひんしつ', 'quality', 'Noun', 'N2', 70, 2, 'business'),
('安定', 'あんてい', 'stability', 'Noun', 'N2', 71, 2, 'business'),
('成長', 'せいちょう', 'growth', 'Noun', 'N2', 72, 2, 'business'),
('回復', 'かいふく', 'recovery', 'Noun', 'N2', 73, 2, 'business'),
('上昇', 'じょうしょう', 'rise/increase', 'Noun', 'N2', 75, 2, 'business'),
('変動', 'へんどう', 'fluctuation/change', 'Noun', 'N2', 76, 3, 'business'),
('課題', 'かだい', 'task/challenge', 'Noun', 'N2', 80, 2, 'business'),
('戦略', 'せんりゃく', 'strategy', 'Noun', 'N2', 81, 3, 'business'),
('進捗', 'しんちょく', 'progress', 'Noun', 'N2', 87, 3, 'business'),
('在庫', 'ざいこ', 'inventory/stock', 'Noun', 'N2', 95, 2, 'business'),
('請求', 'せいきゅう', 'billing/invoice', 'Noun', 'N2', 97, 2, 'business'),
('支援', 'しえん', 'support/assistance', 'Noun', 'N2', 110, 2, 'business'),
('採用', 'さいよう', 'hiring/employment', 'Noun', 'N2', 138, 2, 'business'),
('退職', 'たいしょく', 'retirement/resignation', 'Noun', 'N2', 139, 2, 'business'),
('有給', 'ゆうきゅう', 'paid leave', 'Noun', 'N2', 140, 2, 'business'),
('残業', 'ざんぎょう', 'overtime', 'Noun', 'N2', 141, 2, 'business'),
('出張', 'しゅっちょう', 'business trip', 'Noun', 'N2', 142, 2, 'business'),
('通勤', 'つうきん', 'commuting', 'Noun', 'N2', 145, 2, 'business'),
('昇進', 'しょうしん', 'promotion', 'Noun', 'N2', 132, 2, 'business'),
('転職', 'てんしょく', 'job change', 'Noun', 'N2', 133, 2, 'business'),
('就職', 'しゅうしょく', 'getting a job', 'Noun', 'N2', 134, 2, 'business'),
('失業', 'しつぎょう', 'unemployment', 'Noun', 'N2', 135, 2, 'business'),
('求人', 'きゅうじん', 'job offer/opening', 'Noun', 'N2', 136, 2, 'business'),
('面接', 'めんせつ', 'interview', 'Noun', 'N2', 137, 1, 'business'),
('資格', 'しかく', 'qualification', 'Noun', 'N2', 124, 2, 'business'),
('認定', 'にんてい', 'certification', 'Noun', 'N2', 125, 3, 'business'),
('輸出', 'ゆしゅつ', 'export', 'Noun', 'N2', 130, 2, 'business'),
('輸入', 'ゆにゅう', 'import', 'Noun', 'N2', 131, 2, 'business'),
('貿易', 'ぼうえき', 'trade', 'Noun', 'N2', 132, 2, 'business'),
('税金', 'ぜいきん', 'tax', 'Noun', 'N2', 135, 2, 'business'),
('補助金', 'ほじょきん', 'subsidy/grant', 'Noun', 'N2', 148, 3, 'business'),
('融資', 'ゆうし', 'financing/loan', 'Noun', 'N2', 147, 4, 'business'),
('返済', 'へんさい', 'repayment', 'Noun', 'N2', 146, 3, 'business'),
('慎重', 'しんちょう', 'careful/cautious', 'Adjective', 'N2', 194, 2, 'business'),
('連携', 'れんけい', 'coordination/cooperation', 'Noun', 'N2', 184, 3, 'business'),
('協定', 'きょうてい', 'agreement/pact', 'Noun', 'N2', 183, 3, 'business'),
('主催', 'しゅさい', 'sponsorship/organization', 'Noun', 'N2', 180, 3, 'business');

-- Academic vocabulary (学術用語)
INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('研究', 'けんきゅう', 'research/study', 'Noun', 'N2', 200, 2, 'academic'),
('調査', 'ちょうさ', 'investigation/survey', 'Noun', 'N2', 201, 2, 'academic'),
('分析', 'ぶんせき', 'analysis', 'Noun', 'N2', 202, 2, 'academic'),
('結果', 'けっか', 'result/outcome', 'Noun', 'N2', 203, 1, 'academic'),
('原因', 'げんいん', 'cause/reason', 'Noun', 'N2', 204, 2, 'academic'),
('理論', 'りろん', 'theory', 'Noun', 'N2', 206, 3, 'academic'),
('実験', 'じっけん', 'experiment', 'Noun', 'N2', 207, 2, 'academic'),
('証拠', 'しょうこ', 'evidence/proof', 'Noun', 'N2', 208, 3, 'academic'),
('仮説', 'かせつ', 'hypothesis', 'Noun', 'N2', 209, 4, 'academic'),
('結論', 'けつろん', 'conclusion', 'Noun', 'N2', 210, 2, 'academic'),
('考察', 'こうさつ', 'consideration/examination', 'Noun', 'N2', 211, 4, 'academic'),
('発見', 'はっけん', 'discovery/finding', 'Noun', 'N2', 212, 2, 'academic'),
('証明', 'しょうめい', 'proof/demonstration', 'Noun', 'N2', 213, 2, 'academic'),
('定義', 'ていぎ', 'definition', 'Noun', 'N2', 214, 3, 'academic'),
('概念', 'がいねん', 'concept/notion', 'Noun', 'N2', 215, 4, 'academic'),
('対象', 'たいしょう', 'subject/target', 'Noun', 'N2', 216, 2, 'academic'),
('要因', 'よういん', 'factor/cause', 'Noun', 'N2', 217, 3, 'academic'),
('傾向', 'けいこう', 'tendency/trend', 'Noun', 'N2', 218, 3, 'academic'),
('比較', 'ひかく', 'comparison', 'Noun', 'N2', 219, 2, 'academic'),
('観察', 'かんさつ', 'observation', 'Noun', 'N2', 220, 2, 'academic'),
('測定', 'そくてい', 'measurement', 'Noun', 'N2', 221, 3, 'academic'),
('解釈', 'かいしゃく', 'interpretation', 'Noun', 'N2', 222, 3, 'academic'),
('論文', 'ろんぶん', 'thesis/paper', 'Noun', 'N2', 223, 3, 'academic'),
('統計', 'とうけい', 'statistics', 'Noun', 'N2', 225, 3, 'academic'),
('情報', 'じょうほう', 'information', 'Noun', 'N2', 227, 1, 'academic'),
('知識', 'ちしき', 'knowledge', 'Noun', 'N2', 228, 2, 'academic'),
('理解', 'りかい', 'understanding', 'Noun', 'N2', 229, 1, 'academic'),
('記憶', 'きおく', 'memory', 'Noun', 'N2', 230, 2, 'academic'),
('習慣', 'しゅうかん', 'habit/custom', 'Noun', 'N2', 231, 2, 'academic'),
('規則', 'きそく', 'rule/regulation', 'Noun', 'N2', 232, 2, 'academic'),
('原則', 'げんそく', 'principle/rule', 'Noun', 'N2', 233, 3, 'academic'),
('基礎', 'きそ', 'foundation/basics', 'Noun', 'N2', 234, 2, 'academic'),
('応用', 'おうよう', 'application/applied', 'Noun', 'N2', 235, 3, 'academic'),
('専門', 'せんもん', 'specialty/expertise', 'Noun', 'N2', 236, 2, 'academic'),
('分野', 'ぶんや', 'field/area', 'Noun', 'N2', 237, 2, 'academic'),
('制度', 'せいど', 'system/institution', 'Noun', 'N2', 238, 2, 'academic'),
('機能', 'きのう', 'function/capability', 'Noun', 'N2', 239, 2, 'academic'),
('構造', 'こうぞう', 'structure', 'Noun', 'N2', 240, 3, 'academic'),
('関係', 'かんけい', 'relationship/connection', 'Noun', 'N2', 241, 1, 'academic'),
('要素', 'ようそ', 'element/factor', 'Noun', 'N2', 242, 3, 'academic'),
('条件', 'じょうけん', 'condition/requirement', 'Noun', 'N2', 243, 2, 'academic'),
('特徴', 'とくちょう', 'characteristic/feature', 'Noun', 'N2', 244, 2, 'academic'),
('現象', 'げんしょう', 'phenomenon', 'Noun', 'N2', 245, 3, 'academic'),
('学習', 'がくしゅう', 'learning/study', 'Noun', 'N2', 246, 1, 'academic'),
('教育', 'きょういく', 'education', 'Noun', 'N2', 247, 1, 'academic'),
('授業', 'じゅぎょう', 'class/lesson', 'Noun', 'N2', 248, 1, 'academic'),
('講義', 'こうぎ', 'lecture', 'Noun', 'N2', 249, 2, 'academic'),
('試験', 'しけん', 'examination/test', 'Noun', 'N2', 250, 1, 'academic'),
('成績', 'せいせき', 'grades/results', 'Noun', 'N2', 251, 2, 'academic'),
('能力', 'のうりょく', 'ability/capability', 'Noun', 'N2', 252, 2, 'academic'),
('才能', 'さいのう', 'talent/gift', 'Noun', 'N2', 253, 2, 'academic');

INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('知恵', 'ちえ', 'wisdom', 'Noun', 'N2', 254, 2, 'academic'),
('論理', 'ろんり', 'logic', 'Noun', 'N2', 255, 3, 'academic'),
('思考', 'しこう', 'thinking/thought', 'Noun', 'N2', 256, 3, 'academic'),
('推論', 'すいろん', 'reasoning/inference', 'Noun', 'N2', 257, 4, 'academic'),
('記述', 'きじゅつ', 'description/writing', 'Noun', 'N2', 258, 3, 'academic'),
('説明', 'せつめい', 'explanation', 'Noun', 'N2', 259, 1, 'academic'),
('発表', 'はっぴょう', 'presentation/announcement', 'Noun', 'N2', 260, 2, 'academic'),
('討論', 'とうろん', 'debate/discussion', 'Noun', 'N2', 261, 3, 'academic'),
('意見', 'いけん', 'opinion/view', 'Noun', 'N2', 262, 1, 'academic'),
('主張', 'しゅちょう', 'argument/claim', 'Noun', 'N2', 263, 2, 'academic'),
('反論', 'はんろん', 'counterargument', 'Noun', 'N2', 264, 3, 'academic'),
('賛成', 'さんせい', 'agreement/approval', 'Noun', 'N2', 265, 2, 'academic'),
('反対', 'はんたい', 'opposition/objection', 'Noun', 'N2', 266, 1, 'academic'),
('質問', 'しつもん', 'question', 'Noun', 'N2', 267, 1, 'academic'),
('回答', 'かいとう', 'reply/response', 'Noun', 'N2', 268, 2, 'academic'),
('疑問', 'ぎもん', 'question/doubt', 'Noun', 'N2', 269, 2, 'academic'),
('検討', 'けんとう', 'examination/consideration', 'Noun', 'N2', 270, 2, 'academic'),
('根拠', 'こんきょ', 'basis/ground', 'Noun', 'N2', 271, 3, 'academic'),
('事実', 'じじつ', 'fact', 'Noun', 'N2', 272, 2, 'academic'),
('真実', 'しんじつ', 'truth', 'Noun', 'N2', 273, 2, 'academic'),
('正確', 'せいかく', 'accuracy/precision', 'Adjective', 'N2', 274, 2, 'academic'),
('詳細', 'しょうさい', 'details', 'Noun', 'N2', 275, 2, 'academic'),
('概要', 'がいよう', 'summary/overview', 'Noun', 'N2', 276, 3, 'academic'),
('要約', 'ようやく', 'summary', 'Noun', 'N2', 277, 2, 'academic'),
('参考', 'さんこう', 'reference', 'Noun', 'N2', 278, 2, 'academic'),
('引用', 'いんよう', 'quotation/citation', 'Noun', 'N2', 279, 3, 'academic'),
('客観的', 'きゃっかんてき', 'objective', 'Adjective', 'N2', 280, 3, 'academic'),
('主観的', 'しゅかんてき', 'subjective', 'Adjective', 'N2', 281, 3, 'academic'),
('批判的', 'ひはんてき', 'critical', 'Adjective', 'N2', 282, 3, 'academic'),
('人口', 'じんこう', 'population', 'Noun', 'N2', 283, 1, 'academic'),
('社会', 'しゃかい', 'society', 'Noun', 'N2', 284, 1, 'academic'),
('経済', 'けいざい', 'economy', 'Noun', 'N2', 285, 2, 'academic'),
('科学', 'かがく', 'science', 'Noun', 'N2', 286, 1, 'academic'),
('技術', 'ぎじゅつ', 'technology/technique', 'Noun', 'N2', 287, 2, 'academic'),
('産業', 'さんぎょう', 'industry', 'Noun', 'N2', 288, 2, 'academic'),
('環境', 'かんきょう', 'environment', 'Noun', 'N2', 289, 2, 'academic'),
('少子化', 'しょうしか', 'declining birthrate', 'Noun', 'N2', 290, 3, 'academic'),
('高齢化', 'こうれいか', 'aging population', 'Noun', 'N2', 291, 3, 'academic'),
('格差', 'かくさ', 'disparity/gap', 'Noun', 'N2', 292, 3, 'academic'),
('福祉', 'ふくし', 'welfare', 'Noun', 'N2', 293, 2, 'academic'),
('哲学', 'てつがく', 'philosophy', 'Noun', 'N2', 294, 3, 'academic'),
('思想', 'しそう', 'thought/ideology', 'Noun', 'N2', 295, 3, 'academic'),
('医学', 'いがく', 'medicine/medical science', 'Noun', 'N2', 296, 2, 'academic'),
('農業', 'のうぎょう', 'agriculture', 'Noun', 'N2', 297, 2, 'academic'),
('温暖化', 'おんだんか', 'global warming', 'Noun', 'N2', 298, 2, 'academic'),
('気候変動', 'きこうへんどう', 'climate change', 'Noun', 'N2', 299, 3, 'academic'),
('持続可能', 'じぞくかのう', 'sustainable', 'Adjective', 'N2', 300, 3, 'academic'),
('多様性', 'たようせい', 'diversity', 'Noun', 'N2', 301, 3, 'academic'),
('包摂', 'ほうせつ', 'inclusion', 'Noun', 'N2', 302, 4, 'academic'),
('共生', 'きょうせい', 'coexistence', 'Noun', 'N2', 303, 3, 'academic');

-- Keigo/Formal vocabulary (敬語)
INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('申し上げる', 'もうしあげる', 'to say (humble)', 'Verb', 'N2', 350, 4, 'keigo'),
('いただく', 'いただく', 'to receive (humble)', 'Verb', 'N2', 351, 2, 'keigo'),
('参る', 'まいる', 'to go/come (humble)', 'Verb', 'N2', 352, 3, 'keigo'),
('おっしゃる', 'おっしゃる', 'to say (honorific)', 'Verb', 'N2', 353, 3, 'keigo'),
('いらっしゃる', 'いらっしゃる', 'to be/go/come (honorific)', 'Verb', 'N2', 354, 3, 'keigo'),
('ご覧になる', 'ごらんになる', 'to see (honorific)', 'Verb', 'N2', 355, 3, 'keigo'),
('召し上がる', 'めしあがる', 'to eat/drink (honorific)', 'Verb', 'N2', 356, 3, 'keigo'),
('なさる', 'なさる', 'to do (honorific)', 'Verb', 'N2', 357, 3, 'keigo'),
('お世話になる', 'おせわになる', 'to be in one''s care', 'Expression', 'N2', 358, 2, 'keigo'),
('ご迷惑', 'ごめいわく', 'trouble/inconvenience', 'Noun', 'N2', 359, 2, 'keigo'),
('お願いする', 'おねがいする', 'to request/ask', 'Verb', 'N2', 360, 1, 'keigo'),
('ご確認', 'ごかくにん', 'confirmation (formal)', 'Noun', 'N2', 361, 2, 'keigo'),
('ご連絡', 'ごれんらく', 'contact (formal)', 'Noun', 'N2', 362, 2, 'keigo'),
('拝見する', 'はいけんする', 'to look at (humble)', 'Verb', 'N2', 363, 4, 'keigo'),
('存じる', 'ぞんじる', 'to know (humble)', 'Verb', 'N2', 364, 4, 'keigo'),
('差し上げる', 'さしあげる', 'to give (humble)', 'Verb', 'N2', 365, 3, 'keigo'),
('ご案内', 'ごあんない', 'guidance/information', 'Noun', 'N2', 366, 2, 'keigo'),
('ご利用', 'ごりよう', 'use/utilization (formal)', 'Noun', 'N2', 367, 2, 'keigo'),
('ご挨拶', 'ごあいさつ', 'greeting (formal)', 'Noun', 'N2', 368, 2, 'keigo'),
('お礼', 'おれい', 'thanks/gratitude', 'Noun', 'N2', 369, 2, 'keigo'),
('失礼', 'しつれい', 'rudeness/excuse me', 'Noun', 'N2', 370, 2, 'keigo'),
('恐れ入る', 'おそれいる', 'to be obliged/sorry', 'Verb', 'N2', 371, 4, 'keigo'),
('ご指摘', 'ごしてき', 'pointing out (formal)', 'Noun', 'N2', 372, 3, 'keigo'),
('丁寧', 'ていねい', 'polite/careful', 'Adjective', 'N2', 373, 2, 'keigo'),
('遠慮', 'えんりょ', 'reserve/hesitation', 'Noun', 'N2', 374, 2, 'keigo'),
('配慮', 'はいりょ', 'consideration', 'Noun', 'N2', 375, 3, 'keigo'),
('誠意', 'せいい', 'sincerity/good faith', 'Noun', 'N2', 376, 3, 'keigo'),
('礼儀', 'れいぎ', 'courtesy/manners', 'Noun', 'N2', 377, 3, 'keigo'),
('作法', 'さほう', 'manners/etiquette', 'Noun', 'N2', 378, 3, 'keigo'),
('謙虚', 'けんきょ', 'humility', 'Adjective', 'N2', 379, 3, 'keigo');

-- Daily Life vocabulary (日常会話)
INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('生活', 'せいかつ', 'life/living', 'Noun', 'N2', 400, 1, 'daily'),
('経験', 'けいけん', 'experience', 'Noun', 'N2', 401, 1, 'daily'),
('感じる', 'かんじる', 'to feel/sense', 'Verb', 'N2', 402, 1, 'daily'),
('考える', 'かんがえる', 'to think/consider', 'Verb', 'N2', 403, 1, 'daily'),
('決める', 'きめる', 'to decide', 'Verb', 'N2', 404, 1, 'daily'),
('選ぶ', 'えらぶ', 'to choose/select', 'Verb', 'N2', 405, 1, 'daily'),
('続ける', 'つづける', 'to continue', 'Verb', 'N2', 406, 1, 'daily'),
('変わる', 'かわる', 'to change', 'Verb', 'N2', 407, 1, 'daily'),
('増える', 'ふえる', 'to increase', 'Verb', 'N2', 408, 1, 'daily'),
('減る', 'へる', 'to decrease/reduce', 'Verb', 'N2', 409, 1, 'daily'),
('困る', 'こまる', 'to be troubled/in difficulty', 'Verb', 'N2', 410, 1, 'daily'),
('心配', 'しんぱい', 'worry/concern', 'Noun', 'N2', 411, 1, 'daily'),
('喜ぶ', 'よろこぶ', 'to be glad/rejoice', 'Verb', 'N2', 412, 1, 'daily'),
('楽しむ', 'たのしむ', 'to enjoy', 'Verb', 'N2', 413, 1, 'daily'),
('集中', 'しゅうちゅう', 'concentration/focus', 'Noun', 'N2', 414, 2, 'daily'),
('準備', 'じゅんび', 'preparation', 'Noun', 'N2', 415, 1, 'daily'),
('整理', 'せいり', 'arrangement/organization', 'Noun', 'N2', 416, 2, 'daily'),
('注文', 'ちゅうもん', 'order', 'Noun', 'N2', 417, 1, 'daily'),
('予約', 'よやく', 'reservation/booking', 'Noun', 'N2', 418, 1, 'daily'),
('確かめる', 'たしかめる', 'to confirm/verify', 'Verb', 'N2', 419, 2, 'daily'),
('忘れる', 'わすれる', 'to forget', 'Verb', 'N2', 420, 1, 'daily'),
('思い出す', 'おもいだす', 'to recall/remember', 'Verb', 'N2', 421, 1, 'daily'),
('気づく', 'きづく', 'to notice/realize', 'Verb', 'N2', 422, 2, 'daily'),
('手伝う', 'てつだう', 'to help/assist', 'Verb', 'N2', 423, 1, 'daily'),
('頑張る', 'がんばる', 'to do one''s best', 'Verb', 'N2', 424, 1, 'daily'),
('諦める', 'あきらめる', 'to give up', 'Verb', 'N2', 425, 2, 'daily'),
('我慢する', 'がまんする', 'to endure/be patient', 'Verb', 'N2', 426, 2, 'daily'),
('注意', 'ちゅうい', 'caution/attention', 'Noun', 'N2', 427, 1, 'daily'),
('様子', 'ようす', 'appearance/state', 'Noun', 'N2', 428, 2, 'daily'),
('状態', 'じょうたい', 'condition/state', 'Noun', 'N2', 429, 2, 'daily'),
('場合', 'ばあい', 'case/situation', 'Noun', 'N2', 430, 1, 'daily'),
('場所', 'ばしょ', 'place/location', 'Noun', 'N2', 431, 1, 'daily'),
('理由', 'りゆう', 'reason/cause', 'Noun', 'N2', 432, 1, 'daily'),
('意味', 'いみ', 'meaning/significance', 'Noun', 'N2', 433, 1, 'daily'),
('必要', 'ひつよう', 'necessity/need', 'Noun', 'N2', 434, 1, 'daily'),
('大切', 'たいせつ', 'important/precious', 'Adjective', 'N2', 435, 1, 'daily'),
('安全', 'あんぜん', 'safety/security', 'Noun', 'N2', 436, 1, 'daily'),
('危険', 'きけん', 'danger/risk', 'Noun', 'N2', 437, 1, 'daily'),
('健康', 'けんこう', 'health', 'Noun', 'N2', 438, 1, 'daily'),
('病気', 'びょうき', 'illness/disease', 'Noun', 'N2', 439, 1, 'daily'),
('治る', 'なおる', 'to recover/heal', 'Verb', 'N2', 440, 1, 'daily'),
('運動', 'うんどう', 'exercise/movement', 'Noun', 'N2', 441, 1, 'daily'),
('疲れる', 'つかれる', 'to get tired', 'Verb', 'N2', 442, 1, 'daily'),
('節約', 'せつやく', 'saving/economizing', 'Noun', 'N2', 443, 2, 'daily'),
('旅行', 'りょこう', 'travel', 'Noun', 'N2', 444, 1, 'daily'),
('観光', 'かんこう', 'sightseeing/tourism', 'Noun', 'N2', 445, 1, 'daily'),
('宿泊', 'しゅくはく', 'lodging/accommodation', 'Noun', 'N2', 446, 2, 'daily'),
('保険', 'ほけん', 'insurance', 'Noun', 'N2', 447, 2, 'daily'),
('家族', 'かぞく', 'family', 'Noun', 'N2', 448, 1, 'daily'),
('結婚', 'けっこん', 'marriage', 'Noun', 'N2', 449, 1, 'daily'),
('給料', 'きゅうりょう', 'salary/wages', 'Noun', 'N2', 450, 2, 'daily');

INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('収入', 'しゅうにゅう', 'income', 'Noun', 'N2', 451, 2, 'daily'),
('口座', 'こうざ', 'bank account', 'Noun', 'N2', 452, 2, 'daily'),
('振込', 'ふりこみ', 'bank transfer', 'Noun', 'N2', 453, 2, 'daily'),
('引き出し', 'ひきだし', 'withdrawal', 'Noun', 'N2', 454, 2, 'daily'),
('趣味', 'しゅみ', 'hobby/interest', 'Noun', 'N2', 455, 1, 'daily'),
('映画', 'えいが', 'movie', 'Noun', 'N2', 456, 1, 'daily'),
('音楽', 'おんがく', 'music', 'Noun', 'N2', 457, 1, 'daily'),
('余暇', 'よか', 'leisure time', 'Noun', 'N2', 458, 3, 'daily'),
('娯楽', 'ごらく', 'entertainment', 'Noun', 'N2', 459, 2, 'daily'),
('スポーツ', 'すぽーつ', 'sports', 'Noun', 'N2', 460, 1, 'daily'),
('競技', 'きょうぎ', 'athletic competition', 'Noun', 'N2', 461, 2, 'daily'),
('選手', 'せんしゅ', 'player/athlete', 'Noun', 'N2', 462, 2, 'daily'),
('優勝', 'ゆうしょう', 'championship/victory', 'Noun', 'N2', 463, 2, 'daily'),
('挑戦', 'ちょうせん', 'challenge', 'Noun', 'N2', 464, 2, 'daily'),
('思いやり', 'おもいやり', 'compassion/thoughtfulness', 'Noun', 'N2', 465, 2, 'daily'),
('引っ越し', 'ひっこし', 'moving/relocation', 'Noun', 'N2', 466, 2, 'daily'),
('老後', 'ろうご', 'old age/retirement', 'Noun', 'N2', 467, 2, 'daily'),
('将来', 'しょうらい', 'future', 'Noun', 'N2', 468, 1, 'daily'),
('現在', 'げんざい', 'present/now', 'Noun', 'N2', 469, 1, 'daily'),
('過去', 'かこ', 'past', 'Noun', 'N2', 470, 1, 'daily'),
('目指す', 'めざす', 'to aim for', 'Verb', 'N2', 471, 2, 'daily'),
('達成する', 'たっせいする', 'to achieve', 'Verb', 'N2', 472, 2, 'daily'),
('成功する', 'せいこうする', 'to succeed', 'Verb', 'N2', 473, 1, 'daily'),
('失敗する', 'しっぱいする', 'to fail', 'Verb', 'N2', 474, 1, 'daily'),
('改善する', 'かいぜんする', 'to improve', 'Verb', 'N2', 475, 2, 'daily'),
('確認する', 'かくにんする', 'to confirm', 'Verb', 'N2', 476, 2, 'daily'),
('調べる', 'しらべる', 'to investigate/look up', 'Verb', 'N2', 477, 1, 'daily'),
('乗り越える', 'のりこえる', 'to overcome', 'Verb', 'N2', 478, 2, 'daily'),
('継続する', 'けいぞくする', 'to continue', 'Verb', 'N2', 479, 2, 'daily'),
('守る', 'まもる', 'to protect/observe', 'Verb', 'N2', 480, 1, 'daily'),
('支える', 'ささえる', 'to support', 'Verb', 'N2', 481, 2, 'daily'),
('高める', 'たかめる', 'to raise/enhance', 'Verb', 'N2', 482, 2, 'daily'),
('磨く', 'みがく', 'to polish/refine', 'Verb', 'N2', 483, 2, 'daily'),
('鍛える', 'きたえる', 'to train/forge', 'Verb', 'N2', 484, 2, 'daily'),
('育てる', 'そだてる', 'to raise/cultivate', 'Verb', 'N2', 485, 1, 'daily'),
('冷静', 'れいせい', 'calm/composed', 'Adjective', 'N2', 486, 2, 'daily'),
('素直', 'すなお', 'honest/obedient', 'Adjective', 'N2', 487, 2, 'daily'),
('親切', 'しんせつ', 'kindness', 'Adjective', 'N2', 488, 1, 'daily'),
('正直', 'しょうじき', 'honest', 'Adjective', 'N2', 489, 1, 'daily'),
('真剣', 'しんけん', 'serious/earnest', 'Adjective', 'N2', 490, 2, 'daily'),
('緊急', 'きんきゅう', 'emergency/urgent', 'Adjective', 'N2', 491, 2, 'daily'),
('地震', 'じしん', 'earthquake', 'Noun', 'N2', 492, 1, 'daily'),
('台風', 'たいふう', 'typhoon', 'Noun', 'N2', 493, 1, 'daily'),
('洪水', 'こうずい', 'flood', 'Noun', 'N2', 494, 2, 'daily'),
('避難', 'ひなん', 'evacuation', 'Noun', 'N2', 495, 2, 'daily'),
('事件', 'じけん', 'incident/case', 'Noun', 'N2', 496, 2, 'daily'),
('事故', 'じこ', 'accident', 'Noun', 'N2', 497, 1, 'daily'),
('節電', 'せつでん', 'energy saving', 'Noun', 'N2', 498, 2, 'daily'),
('寄付', 'きふ', 'donation', 'Noun', 'N2', 499, 2, 'daily'),
('ボランティア', 'ぼらんてぃあ', 'volunteer', 'Noun', 'N2', 500, 1, 'daily');

-- Idioms & Proverbs (ことわざ・慣用句)
INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('一石二鳥', 'いっせきにちょう', 'killing two birds with one stone', 'Expression', 'N2', 550, 3, 'idioms'),
('七転び八起き', 'ななころびやおき', 'fall seven times stand up eight (perseverance)', 'Expression', 'N2', 551, 3, 'idioms'),
('花より団子', 'はなよりだんご', 'substance over appearance (practical over beautiful)', 'Expression', 'N2', 552, 3, 'idioms'),
('急がば回れ', 'いそがばまわれ', 'more haste less speed', 'Expression', 'N2', 553, 3, 'idioms'),
('習うより慣れろ', 'ならうよりなれろ', 'practice makes perfect', 'Expression', 'N2', 554, 3, 'idioms'),
('石の上にも三年', 'いしのうえにもさんねん', 'perseverance prevails', 'Expression', 'N2', 555, 3, 'idioms'),
('猫に小判', 'ねこにこばん', 'pearls before swine', 'Expression', 'N2', 556, 3, 'idioms'),
('出る杭は打たれる', 'でるくいはうたれる', 'the nail that sticks out gets hammered', 'Expression', 'N2', 557, 3, 'idioms'),
('頭が上がらない', 'あたまがあがらない', 'can''t hold head up (feel inferior to someone)', 'Expression', 'N2', 558, 3, 'idioms'),
('手を貸す', 'てをかす', 'to lend a hand/help', 'Expression', 'N2', 559, 3, 'idioms'),
('目をつける', 'めをつける', 'to have one''s eye on something', 'Expression', 'N2', 560, 3, 'idioms'),
('気が合う', 'きがあう', 'to get along well', 'Expression', 'N2', 561, 2, 'idioms'),
('口が堅い', 'くちがかたい', 'tight-lipped/discreet', 'Expression', 'N2', 562, 3, 'idioms'),
('腕が上がる', 'うでがあがる', 'skill improves', 'Expression', 'N2', 563, 3, 'idioms'),
('足が出る', 'あしがでる', 'to go over budget', 'Expression', 'N2', 564, 3, 'idioms'),
('胸を張る', 'むねをはる', 'to be proud/confident', 'Expression', 'N2', 565, 3, 'idioms'),
('肩を持つ', 'かたをもつ', 'to take someone''s side', 'Expression', 'N2', 566, 3, 'idioms'),
('鼻が高い', 'はながたかい', 'to be proud', 'Expression', 'N2', 567, 3, 'idioms'),
('後悔先に立たず', 'こうかいさきにたたず', 'no use crying over spilled milk', 'Expression', 'N2', 568, 3, 'idioms'),
('継続は力なり', 'けいぞくはちからなり', 'persistence is power', 'Expression', 'N2', 569, 3, 'idioms'),
('知らぬが仏', 'しらぬがほとけ', 'ignorance is bliss', 'Expression', 'N2', 570, 3, 'idioms'),
('備えあれば憂いなし', 'そなえあればうれいなし', 'be prepared for anything', 'Expression', 'N2', 571, 3, 'idioms'),
('好きこそものの上手なれ', 'すきこそもののじょうずなれ', 'love what you do to excel', 'Expression', 'N2', 572, 4, 'idioms'),
('二兎を追う者は一兎も得ず', 'にとをおうものはいちともえず', 'chase two hares catch none', 'Expression', 'N2', 573, 4, 'idioms'),
('案ずるより産むが易し', 'あんずるよりうむがやすし', 'easier done than said', 'Expression', 'N2', 574, 4, 'idioms'),
('目から鱗が落ちる', 'めからうろこがおちる', 'scales fall from one''s eyes (sudden realization)', 'Expression', 'N2', 575, 3, 'idioms'),
('棚からぼたもち', 'たなからぼたもち', 'a windfall/lucky break', 'Expression', 'N2', 576, 3, 'idioms'),
('七難八苦', 'しちなんはっく', 'many hardships and difficulties', 'Expression', 'N2', 577, 4, 'idioms'),
('一期一会', 'いちごいちえ', 'once in a lifetime encounter', 'Expression', 'N2', 578, 4, 'idioms'),
('以心伝心', 'いしんでんしん', 'telepathy/mutual understanding', 'Expression', 'N2', 579, 4, 'idioms');

-- Kanji Compounds (漢字語)
INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('政治', 'せいじ', 'politics', 'Noun', 'N2', 600, 2, 'kanji'),
('文化', 'ぶんか', 'culture', 'Noun', 'N2', 601, 1, 'kanji'),
('歴史', 'れきし', 'history', 'Noun', 'N2', 602, 2, 'kanji'),
('自然', 'しぜん', 'nature', 'Noun', 'N2', 603, 1, 'kanji'),
('資源', 'しげん', 'resources', 'Noun', 'N2', 604, 2, 'kanji'),
('地球', 'ちきゅう', 'Earth/globe', 'Noun', 'N2', 605, 1, 'kanji'),
('国際', 'こくさい', 'international', 'Adjective', 'N2', 606, 2, 'kanji'),
('法律', 'ほうりつ', 'law', 'Noun', 'N2', 607, 2, 'kanji'),
('権利', 'けんり', 'right/privilege', 'Noun', 'N2', 608, 2, 'kanji'),
('義務', 'ぎむ', 'duty/obligation', 'Noun', 'N2', 609, 2, 'kanji'),
('責任', 'せきにん', 'responsibility', 'Noun', 'N2', 610, 2, 'kanji'),
('自由', 'じゆう', 'freedom/liberty', 'Noun', 'N2', 611, 1, 'kanji'),
('平等', 'びょうどう', 'equality', 'Noun', 'N2', 612, 2, 'kanji'),
('正義', 'せいぎ', 'justice', 'Noun', 'N2', 613, 2, 'kanji'),
('価値', 'かち', 'value/worth', 'Noun', 'N2', 614, 2, 'kanji'),
('信頼', 'しんらい', 'trust/confidence', 'Noun', 'N2', 615, 2, 'kanji'),
('協力', 'きょうりょく', 'cooperation', 'Noun', 'N2', 616, 2, 'kanji'),
('競争', 'きょうそう', 'competition', 'Noun', 'N2', 617, 2, 'kanji'),
('発展', 'はってん', 'development/growth', 'Noun', 'N2', 618, 2, 'kanji'),
('進歩', 'しんぽ', 'progress/advance', 'Noun', 'N2', 619, 2, 'kanji'),
('革新', 'かくしん', 'innovation/reform', 'Noun', 'N2', 620, 3, 'kanji'),
('創造', 'そうぞう', 'creation', 'Noun', 'N2', 621, 3, 'kanji'),
('想像', 'そうぞう', 'imagination', 'Noun', 'N2', 622, 2, 'kanji'),
('表現', 'ひょうげん', 'expression', 'Noun', 'N2', 623, 2, 'kanji'),
('芸術', 'げいじゅつ', 'art', 'Noun', 'N2', 624, 2, 'kanji'),
('文学', 'ぶんがく', 'literature', 'Noun', 'N2', 625, 2, 'kanji'),
('都市', 'とし', 'city', 'Noun', 'N2', 626, 1, 'kanji'),
('地域', 'ちいき', 'region/area', 'Noun', 'N2', 627, 2, 'kanji'),
('伝統', 'でんとう', 'tradition', 'Noun', 'N2', 628, 2, 'kanji'),
('宗教', 'しゅうきょう', 'religion', 'Noun', 'N2', 629, 2, 'kanji'),
('行事', 'ぎょうじ', 'event/ceremony', 'Noun', 'N2', 630, 2, 'kanji'),
('調和', 'ちょうわ', 'harmony', 'Noun', 'N2', 631, 3, 'kanji'),
('統一', 'とういつ', 'unification', 'Noun', 'N2', 632, 2, 'kanji'),
('意識', 'いしき', 'consciousness/awareness', 'Noun', 'N2', 633, 2, 'kanji'),
('誠実', 'せいじつ', 'sincere', 'Adjective', 'N2', 634, 3, 'kanji'),
('積極的', 'せっきょくてき', 'positive/active', 'Adjective', 'N2', 635, 2, 'kanji'),
('好奇心', 'こうきしん', 'curiosity', 'Noun', 'N2', 636, 3, 'kanji'),
('向上心', 'こうじょうしん', 'ambition/desire to improve', 'Noun', 'N2', 637, 3, 'kanji'),
('達成感', 'たっせいかん', 'sense of achievement', 'Noun', 'N2', 638, 3, 'kanji'),
('充実感', 'じゅうじつかん', 'sense of fulfillment', 'Noun', 'N2', 639, 3, 'kanji'),
('余裕', 'よゆう', 'margin/leeway', 'Noun', 'N2', 640, 2, 'kanji'),
('建設', 'けんせつ', 'construction', 'Noun', 'N2', 641, 2, 'kanji'),
('交通', 'こうつう', 'traffic/transportation', 'Noun', 'N2', 642, 1, 'kanji'),
('通信', 'つうしん', 'communication', 'Noun', 'N2', 643, 2, 'kanji'),
('放送', 'ほうそう', 'broadcast', 'Noun', 'N2', 644, 2, 'kanji'),
('出版', 'しゅっぱん', 'publication', 'Noun', 'N2', 645, 3, 'kanji'),
('工業', 'こうぎょう', 'manufacturing/industry', 'Noun', 'N2', 646, 2, 'kanji'),
('独創的', 'どくそうてき', 'original/creative', 'Adjective', 'N2', 647, 3, 'kanji'),
('革新的', 'かくしんてき', 'innovative', 'Adjective', 'N2', 648, 3, 'kanji'),
('現代的', 'げんだいてき', 'contemporary', 'Adjective', 'N2', 649, 2, 'kanji'),
('時代遅れ', 'じだいおくれ', 'outdated', 'Adjective', 'N2', 650, 2, 'kanji');

-- Additional vocabulary (mixed categories for completeness)
INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('さらに', 'さらに', 'furthermore/additionally', 'Adverb', 'N2', 700, 1, 'daily'),
('一方', 'いっぽう', 'on the other hand', 'Conjunction', 'N2', 701, 2, 'academic'),
('つまり', 'つまり', 'in other words', 'Conjunction', 'N2', 702, 1, 'academic'),
('したがって', 'したがって', 'therefore', 'Conjunction', 'N2', 703, 2, 'academic'),
('特に', 'とくに', 'especially/particularly', 'Adverb', 'N2', 704, 1, 'daily'),
('全体的に', 'ぜんたいてきに', 'overall', 'Adverb', 'N2', 705, 2, 'academic'),
('基本的に', 'きほんてきに', 'basically', 'Adverb', 'N2', 706, 2, 'academic'),
('実際には', 'じっさいには', 'in reality/actually', 'Adverb', 'N2', 707, 2, 'academic'),
('効果的に', 'こうかてきに', 'effectively', 'Adverb', 'N2', 708, 2, 'business'),
('積極的に', 'せっきょくてきに', 'actively/positively', 'Adverb', 'N2', 709, 2, 'business'),
('確かに', 'たしかに', 'certainly/indeed', 'Adverb', 'N2', 710, 2, 'academic'),
('当然', 'とうぜん', 'naturally/of course', 'Adverb', 'N2', 711, 2, 'academic'),
('偶然', 'ぐうぜん', 'accidentally/by chance', 'Adverb', 'N2', 712, 2, 'daily'),
('丁寧に', 'ていねいに', 'politely/carefully', 'Adverb', 'N2', 713, 2, 'keigo'),
('迅速に', 'じんそくに', 'quickly/swiftly', 'Adverb', 'N2', 714, 3, 'business'),
('円滑に', 'えんかつに', 'smoothly', 'Adverb', 'N2', 715, 3, 'business'),
('認識', 'にんしき', 'recognition/awareness', 'Noun', 'N2', 716, 3, 'academic'),
('把握', 'はあく', 'grasp/understanding', 'Noun', 'N2', 717, 3, 'academic'),
('整合性', 'せいごうせい', 'consistency', 'Noun', 'N2', 718, 4, 'academic'),
('矛盾', 'むじゅん', 'contradiction', 'Noun', 'N2', 719, 3, 'academic'),
('類似', 'るいじ', 'similarity', 'Noun', 'N2', 720, 3, 'academic'),
('相違', 'そうい', 'difference', 'Noun', 'N2', 721, 3, 'academic'),
('共通点', 'きょうつうてん', 'common point', 'Noun', 'N2', 722, 2, 'academic'),
('長所', 'ちょうしょ', 'strong point/advantage', 'Noun', 'N2', 723, 2, 'daily'),
('短所', 'たんしょ', 'weak point/disadvantage', 'Noun', 'N2', 724, 2, 'daily'),
('強み', 'つよみ', 'strength', 'Noun', 'N2', 725, 2, 'business'),
('弱み', 'よわみ', 'weakness', 'Noun', 'N2', 726, 2, 'business'),
('機会', 'きかい', 'opportunity/chance', 'Noun', 'N2', 727, 2, 'business'),
('危機', 'きき', 'crisis', 'Noun', 'N2', 728, 2, 'academic'),
('課題', 'かだい', 'task/challenge', 'Noun', 'N2', 729, 2, 'business'),
('段階', 'だんかい', 'stage/phase', 'Noun', 'N2', 730, 2, 'academic'),
('過程', 'かてい', 'process', 'Noun', 'N2', 731, 2, 'academic'),
('方策', 'ほうさく', 'measure/plan', 'Noun', 'N2', 732, 3, 'business'),
('工夫', 'くふう', 'ingenuity/device', 'Noun', 'N2', 733, 2, 'daily'),
('発想', 'はっそう', 'idea/inspiration', 'Noun', 'N2', 734, 3, 'academic'),
('指示', 'しじ', 'instruction/direction', 'Noun', 'N2', 735, 2, 'business'),
('依頼', 'いらい', 'request/commission', 'Noun', 'N2', 736, 2, 'business'),
('委託', 'いたく', 'consignment/entrust', 'Noun', 'N2', 737, 3, 'business'),
('代理', 'だいり', 'proxy/agent', 'Noun', 'N2', 738, 2, 'business'),
('後援', 'こうえん', 'backing/sponsorship', 'Noun', 'N2', 739, 3, 'business'),
('合意', 'ごうい', 'agreement/consensus', 'Noun', 'N2', 740, 2, 'business'),
('妥協', 'だきょう', 'compromise', 'Noun', 'N2', 741, 3, 'business'),
('解決策', 'かいけつさく', 'solution', 'Noun', 'N2', 742, 2, 'business'),
('最善策', 'さいぜんさく', 'best plan', 'Noun', 'N2', 743, 3, 'business'),
('一時的', 'いちじてき', 'temporary', 'Adjective', 'N2', 744, 2, 'daily'),
('継続的', 'けいぞくてき', 'continuous/sustained', 'Adjective', 'N2', 745, 3, 'business'),
('定期的', 'ていきてき', 'periodic/regular', 'Adjective', 'N2', 746, 2, 'business'),
('計画的', 'けいかくてき', 'planned/systematic', 'Adjective', 'N2', 747, 3, 'business'),
('総合的', 'そうごうてき', 'comprehensive/overall', 'Adjective', 'N2', 748, 3, 'business'),
('包括的', 'ほうかつてき', 'comprehensive', 'Adjective', 'N2', 749, 4, 'academic'),
('具体的な', 'ぐたいてきな', 'concrete/specific', 'Adjective', 'N2', 750, 2, 'academic');

INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('抽象的な', 'ちゅうしょうてきな', 'abstract', 'Adjective', 'N2', 751, 3, 'academic'),
('普遍的な', 'ふへんてきな', 'universal', 'Adjective', 'N2', 752, 4, 'academic'),
('特殊な', 'とくしゅな', 'special/unusual', 'Adjective', 'N2', 753, 2, 'academic'),
('曖昧な', 'あいまいな', 'vague/ambiguous', 'Adjective', 'N2', 754, 3, 'daily'),
('明確な', 'めいかくな', 'clear/definite', 'Adjective', 'N2', 755, 2, 'business'),
('複雑な', 'ふくざつな', 'complex/complicated', 'Adjective', 'N2', 756, 2, 'daily'),
('顕著な', 'けんちょな', 'remarkable/notable', 'Adjective', 'N2', 757, 3, 'academic'),
('著しい', 'いちじるしい', 'remarkable/striking', 'Adjective', 'N2', 758, 3, 'academic'),
('わずかな', 'わずかな', 'slight/minimal', 'Adjective', 'N2', 759, 2, 'daily'),
('微妙な', 'びみょうな', 'subtle/delicate', 'Adjective', 'N2', 760, 2, 'daily'),
('画期的', 'かっきてき', 'epoch-making', 'Adjective', 'N2', 761, 4, 'academic'),
('劇的', 'げきてき', 'dramatic', 'Adjective', 'N2', 762, 3, 'academic'),
('大胆', 'だいたん', 'bold/daring', 'Adjective', 'N2', 763, 2, 'kanji'),
('情熱的', 'じょうねつてき', 'passionate', 'Adjective', 'N2', 764, 3, 'daily'),
('熱心', 'ねっしん', 'enthusiastic/eager', 'Adjective', 'N2', 765, 2, 'daily'),
('活発', 'かっぱつ', 'lively/active', 'Adjective', 'N2', 766, 2, 'daily'),
('穏やか', 'おだやか', 'calm/gentle', 'Adjective', 'N2', 767, 2, 'daily'),
('温かさ', 'あたたかさ', 'warmth', 'Noun', 'N2', 768, 2, 'daily'),
('厳しさ', 'きびしさ', 'strictness', 'Noun', 'N2', 769, 2, 'daily'),
('優しさ', 'やさしさ', 'kindness/gentleness', 'Noun', 'N2', 770, 2, 'daily'),
('共感', 'きょうかん', 'empathy', 'Noun', 'N2', 771, 3, 'daily'),
('尊重', 'そんちょう', 'respect/esteem', 'Noun', 'N2', 772, 3, 'kanji'),
('相互理解', 'そうごりかい', 'mutual understanding', 'Noun', 'N2', 773, 3, 'academic'),
('連帯', 'れんたい', 'solidarity', 'Noun', 'N2', 774, 3, 'kanji'),
('帰属意識', 'きぞくいしき', 'sense of belonging', 'Noun', 'N2', 775, 4, 'academic'),
('自己実現', 'じこじつげん', 'self-actualization', 'Noun', 'N2', 776, 4, 'academic'),
('コミュニケーション', 'こみゅにけーしょん', 'communication', 'Noun', 'N2', 777, 1, 'daily'),
('対話', 'たいわ', 'dialogue', 'Noun', 'N2', 778, 2, 'academic'),
('議論', 'ぎろん', 'debate/discussion', 'Noun', 'N2', 779, 2, 'academic'),
('診断', 'しんだん', 'diagnosis', 'Noun', 'N2', 780, 2, 'daily'),
('治療', 'ちりょう', 'treatment', 'Noun', 'N2', 781, 2, 'daily'),
('症状', 'しょうじょう', 'symptoms', 'Noun', 'N2', 782, 2, 'daily'),
('感染', 'かんせん', 'infection', 'Noun', 'N2', 783, 2, 'daily'),
('予防接種', 'よぼうせっしゅ', 'vaccination', 'Noun', 'N2', 784, 3, 'daily'),
('免疫', 'めんえき', 'immunity', 'Noun', 'N2', 785, 3, 'academic'),
('介護', 'かいご', 'nursing care', 'Noun', 'N2', 786, 2, 'daily'),
('看護', 'かんご', 'nursing', 'Noun', 'N2', 787, 2, 'daily'),
('バリアフリー', 'ばりあふりー', 'barrier-free', 'Noun', 'N2', 788, 2, 'daily'),
('AI', 'えーあい', 'artificial intelligence', 'Noun', 'N2', 789, 1, 'academic'),
('機械学習', 'きかいがくしゅう', 'machine learning', 'Noun', 'N2', 790, 3, 'academic'),
('データ分析', 'でーたぶんせき', 'data analysis', 'Noun', 'N2', 791, 2, 'academic'),
('セキュリティ', 'せきゅりてぃ', 'security', 'Noun', 'N2', 792, 2, 'business'),
('プライバシー', 'ぷらいばしー', 'privacy', 'Noun', 'N2', 793, 1, 'daily'),
('個人情報', 'こじんじょうほう', 'personal information', 'Noun', 'N2', 794, 2, 'daily'),
('デジタル化', 'でじたるか', 'digitalization', 'Noun', 'N2', 795, 2, 'business'),
('自動化する', 'じどうかする', 'to automate', 'Verb', 'N2', 796, 3, 'business'),
('最先端', 'さいせんたん', 'cutting-edge', 'Noun', 'N2', 797, 3, 'academic'),
('昨今', 'さっこん', 'recently/nowadays', 'Noun', 'N2', 798, 3, 'academic'),
('見通し', 'みとおし', 'outlook/prospects', 'Noun', 'N2', 799, 3, 'business'),
('展望', 'てんぼう', 'outlook/view', 'Noun', 'N2', 800, 3, 'academic');

INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('実現する', 'じつげんする', 'to realize/achieve', 'Verb', 'N2', 801, 2, 'business'),
('維持する', 'いじする', 'to maintain', 'Verb', 'N2', 802, 2, 'business'),
('補う', 'おぎなう', 'to supplement/compensate', 'Verb', 'N2', 803, 3, 'academic'),
('転換する', 'てんかんする', 'to convert/transform', 'Verb', 'N2', 804, 3, 'academic'),
('変革する', 'へんかくする', 'to reform/transform', 'Verb', 'N2', 805, 4, 'academic'),
('省略する', 'しょうりゃくする', 'to abbreviate/omit', 'Verb', 'N2', 806, 3, 'academic'),
('含む', 'ふくむ', 'to include/contain', 'Verb', 'N2', 807, 2, 'academic'),
('除く', 'のぞく', 'to exclude', 'Verb', 'N2', 808, 2, 'academic'),
('扱う', 'あつかう', 'to handle/treat', 'Verb', 'N2', 809, 2, 'business'),
('応じる', 'おうじる', 'to respond/comply', 'Verb', 'N2', 810, 2, 'daily'),
('従う', 'したがう', 'to follow/obey', 'Verb', 'N2', 811, 2, 'daily'),
('遵守する', 'じゅんしゅする', 'to comply with', 'Verb', 'N2', 812, 4, 'business'),
('違反する', 'いはんする', 'to violate', 'Verb', 'N2', 813, 2, 'daily'),
('満たす', 'みたす', 'to satisfy/fulfill', 'Verb', 'N2', 814, 2, 'academic'),
('不足する', 'ふそくする', 'to be insufficient', 'Verb', 'N2', 815, 2, 'daily'),
('超過する', 'ちょうかする', 'to exceed', 'Verb', 'N2', 816, 3, 'business'),
('削除する', 'さくじょする', 'to delete', 'Verb', 'N2', 817, 2, 'daily'),
('保存する', 'ほぞんする', 'to save/preserve', 'Verb', 'N2', 818, 2, 'daily'),
('更新する', 'こうしんする', 'to update/renew', 'Verb', 'N2', 819, 2, 'daily'),
('検証する', 'けんしょうする', 'to verify', 'Verb', 'N2', 820, 3, 'academic'),
('探る', 'さぐる', 'to probe/explore', 'Verb', 'N2', 821, 3, 'academic'),
('追求する', 'ついきゅうする', 'to pursue', 'Verb', 'N2', 822, 3, 'academic'),
('果たす', 'はたす', 'to fulfill/accomplish', 'Verb', 'N2', 823, 2, 'kanji'),
('遂げる', 'とげる', 'to accomplish', 'Verb', 'N2', 824, 3, 'kanji'),
('養う', 'やしなう', 'to support/nurture', 'Verb', 'N2', 825, 3, 'kanji'),
('解消する', 'かいしょうする', 'to dissolve/resolve', 'Verb', 'N2', 826, 3, 'daily'),
('推奨', 'すいしょう', 'recommendation', 'Noun', 'N2', 827, 3, 'business'),
('促進', 'そくしん', 'promotion/facilitation', 'Noun', 'N2', 828, 3, 'business'),
('規制', 'きせい', 'regulation/control', 'Noun', 'N2', 829, 3, 'business'),
('禁止', 'きんし', 'prohibition', 'Noun', 'N2', 830, 2, 'daily'),
('制限', 'せいげん', 'limitation/restriction', 'Noun', 'N2', 831, 2, 'business'),
('施行', 'しこう', 'enforcement/implementation', 'Noun', 'N2', 832, 4, 'business'),
('適用', 'てきよう', 'application', 'Noun', 'N2', 833, 3, 'business'),
('例外', 'れいがい', 'exception', 'Noun', 'N2', 834, 2, 'academic'),
('改正', 'かいせい', 'revision/amendment', 'Noun', 'N2', 835, 3, 'business'),
('対処', 'たいしょ', 'dealing with/handling', 'Noun', 'N2', 836, 3, 'business'),
('措置', 'そち', 'measures/steps', 'Noun', 'N2', 837, 3, 'business'),
('不況', 'ふきょう', 'recession', 'Noun', 'N2', 838, 3, 'business'),
('景気', 'けいき', 'economic conditions', 'Noun', 'N2', 839, 2, 'business'),
('物価', 'ぶっか', 'prices', 'Noun', 'N2', 840, 2, 'business'),
('賃金', 'ちんぎん', 'wages', 'Noun', 'N2', 841, 3, 'business'),
('雇用', 'こよう', 'employment', 'Noun', 'N2', 842, 2, 'business'),
('解雇する', 'かいこする', 'to dismiss/fire', 'Verb', 'N2', 843, 3, 'business'),
('仮説', 'かせつ', 'hypothesis', 'Noun', 'N2', 844, 4, 'academic'),
('検討する', 'けんとうする', 'to examine/consider', 'Verb', 'N2', 845, 2, 'business'),
('方針を立てる', 'ほうしんをたてる', 'to set a policy', 'Expression', 'N2', 846, 3, 'business'),
('見解を述べる', 'けんかいをのべる', 'to state one''s view', 'Expression', 'N2', 847, 3, 'academic'),
('立場を明確にする', 'たちばをめいかくにする', 'to clarify one''s position', 'Expression', 'N2', 848, 3, 'business'),
('意識を高める', 'いしきをたかめる', 'to raise awareness', 'Expression', 'N2', 849, 3, 'academic'),
('課題を克服する', 'かだいをこくふくする', 'to overcome challenges', 'Expression', 'N2', 850, 3, 'business');

INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('効率化する', 'こうりつかする', 'to make efficient', 'Verb', 'N2', 851, 3, 'business'),
('標準化する', 'ひょうじゅんかする', 'to standardize', 'Verb', 'N2', 852, 4, 'business'),
('多角的', 'たかくてき', 'multifaceted', 'Adjective', 'N2', 853, 4, 'academic'),
('独自の', 'どくじの', 'unique/original', 'Adjective', 'N2', 854, 2, 'academic'),
('先進的', 'せんしんてき', 'advanced', 'Adjective', 'N2', 855, 3, 'academic'),
('保守的', 'ほしゅてき', 'conservative', 'Adjective', 'N2', 856, 3, 'academic'),
('伝統的', 'でんとうてき', 'traditional', 'Adjective', 'N2', 857, 2, 'academic'),
('本格的', 'ほんかくてき', 'full-scale/genuine', 'Adjective', 'N2', 858, 3, 'business'),
('試験的', 'しけんてき', 'experimental', 'Adjective', 'N2', 859, 3, 'academic'),
('恒久的', 'こうきゅうてき', 'permanent', 'Adjective', 'N2', 860, 4, 'academic'),
('暫定的', 'ざんていてき', 'provisional/tentative', 'Adjective', 'N2', 861, 4, 'business'),
('突発的', 'とっぱつてき', 'sudden/unexpected', 'Adjective', 'N2', 862, 4, 'daily'),
('組織的', 'そしきてき', 'organized/systematic', 'Adjective', 'N2', 863, 3, 'business'),
('体系的', 'たいけいてき', 'systematic', 'Adjective', 'N2', 864, 4, 'academic'),
('統合的', 'とうごうてき', 'integrated', 'Adjective', 'N2', 865, 4, 'academic'),
('感情的', 'かんじょうてき', 'emotional', 'Adjective', 'N2', 866, 2, 'daily'),
('理性的', 'りせいてき', 'rational', 'Adjective', 'N2', 867, 3, 'academic'),
('均衡', 'きんこう', 'balance/equilibrium', 'Noun', 'N2', 868, 4, 'academic'),
('推移', 'すいい', 'transition/change', 'Noun', 'N2', 869, 3, 'academic'),
('背景', 'はいけい', 'background', 'Noun', 'N2', 870, 2, 'academic'),
('動機', 'どうき', 'motivation/motive', 'Noun', 'N2', 871, 3, 'academic'),
('目的意識', 'もくてきいしき', 'sense of purpose', 'Noun', 'N2', 872, 3, 'academic'),
('水準', 'すいじゅん', 'level/standard', 'Noun', 'N2', 873, 3, 'academic'),
('平均', 'へいきん', 'average', 'Noun', 'N2', 874, 1, 'academic'),
('割合', 'わりあい', 'ratio/percentage', 'Noun', 'N2', 875, 2, 'academic'),
('範囲', 'はんい', 'range/scope', 'Noun', 'N2', 876, 2, 'academic'),
('規模', 'きぼ', 'scale/size', 'Noun', 'N2', 877, 2, 'business'),
('程度', 'ていど', 'degree/extent', 'Noun', 'N2', 878, 2, 'daily'),
('上限', 'じょうげん', 'upper limit', 'Noun', 'N2', 879, 3, 'business'),
('下限', 'かげん', 'lower limit', 'Noun', 'N2', 880, 3, 'business'),
('最大値', 'さいだいち', 'maximum value', 'Noun', 'N2', 881, 3, 'academic'),
('最小値', 'さいしょうち', 'minimum value', 'Noun', 'N2', 882, 3, 'academic'),
('誠実さ', 'せいじつさ', 'sincerity', 'Noun', 'N2', 883, 3, 'kanji'),
('信用', 'しんよう', 'trust/credit', 'Noun', 'N2', 884, 2, 'business'),
('公正', 'こうせい', 'fair/just', 'Adjective', 'N2', 885, 3, 'kanji'),
('中立', 'ちゅうりつ', 'neutrality', 'Noun', 'N2', 886, 3, 'academic'),
('偏見', 'へんけん', 'prejudice/bias', 'Noun', 'N2', 887, 3, 'academic'),
('差別', 'さべつ', 'discrimination', 'Noun', 'N2', 888, 3, 'academic'),
('不公平', 'ふこうへい', 'unfair', 'Adjective', 'N2', 889, 2, 'daily'),
('相互', 'そうご', 'mutual/reciprocal', 'Adjective', 'N2', 890, 3, 'business'),
('組織', 'そしき', 'organization/structure', 'Noun', 'N2', 891, 2, 'academic'),
('道徳', 'どうとく', 'morality/ethics', 'Noun', 'N2', 892, 3, 'kanji'),
('品格', 'ひんかく', 'dignity/character', 'Noun', 'N2', 893, 4, 'kanji'),
('礼節', 'れいせつ', 'courtesy/etiquette', 'Noun', 'N2', 894, 3, 'keigo'),
('謙遜', 'けんそん', 'humility/modesty', 'Noun', 'N2', 895, 4, 'kanji'),
('寛容', 'かんよう', 'tolerance', 'Noun', 'N2', 896, 3, 'kanji'),
('辛抱', 'しんぼう', 'patience/endurance', 'Noun', 'N2', 897, 3, 'daily'),
('根気', 'こんき', 'perseverance/patience', 'Noun', 'N2', 898, 3, 'daily'),
('精進', 'しょうじん', 'devotion/diligence', 'Noun', 'N2', 899, 4, 'kanji'),
('初志貫徹', 'しょしかんてつ', 'sticking to one''s original intention', 'Expression', 'N2', 900, 4, 'idioms');

INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('努力を惜しまない', 'どりょくをおしまない', 'to spare no effort', 'Expression', 'N2', 901, 3, 'idioms'),
('試行錯誤', 'しこうさくご', 'trial and error', 'Expression', 'N2', 902, 3, 'academic'),
('切磋琢磨', 'せっさたくま', 'mutual improvement through competition', 'Expression', 'N2', 903, 4, 'idioms'),
('温故知新', 'おんこちしん', 'learning from the past to understand the present', 'Expression', 'N2', 904, 4, 'idioms'),
('以上', 'いじょう', 'above/more than/that is all', 'Expression', 'N2', 905, 1, 'academic'),
('以下', 'いか', 'below/less than/as follows', 'Expression', 'N2', 906, 1, 'academic'),
('以外', 'いがい', 'other than/except', 'Expression', 'N2', 907, 1, 'daily'),
('以内', 'いない', 'within/inside', 'Expression', 'N2', 908, 2, 'daily'),
('ところが', 'ところが', 'however/but', 'Conjunction', 'N2', 909, 2, 'daily'),
('もっとも', 'もっとも', 'however/though', 'Conjunction', 'N2', 910, 3, 'academic'),
('すなわち', 'すなわち', 'namely/that is', 'Conjunction', 'N2', 911, 3, 'academic'),
('なお', 'なお', 'furthermore/still/in addition', 'Conjunction', 'N2', 912, 2, 'academic'),
('および', 'および', 'and/as well as', 'Conjunction', 'N2', 913, 2, 'academic'),
('かつ', 'かつ', 'and/also/at the same time', 'Conjunction', 'N2', 914, 3, 'academic'),
('又は', 'または', 'or', 'Conjunction', 'N2', 915, 2, 'academic'),
('に関して', 'にかんして', 'regarding/concerning', 'Expression', 'N2', 916, 2, 'academic'),
('に対して', 'にたいして', 'toward/against', 'Expression', 'N2', 917, 2, 'academic'),
('によって', 'によって', 'by means of/depending on', 'Expression', 'N2', 918, 2, 'academic'),
('において', 'において', 'in/at/regarding', 'Expression', 'N2', 919, 2, 'academic'),
('に基づいて', 'にもとづいて', 'based on', 'Expression', 'N2', 920, 2, 'academic'),
('にもかかわらず', 'にもかかわらず', 'despite/in spite of', 'Expression', 'N2', 921, 3, 'academic'),
('ともに', 'ともに', 'together/along with', 'Expression', 'N2', 922, 2, 'academic'),
('向けに', 'むけに', 'aimed at/for', 'Expression', 'N2', 923, 2, 'daily'),
('として', 'として', 'as/in the capacity of', 'Expression', 'N2', 924, 1, 'academic'),
('一般的な', 'いっぱんてきな', 'general/common', 'Adjective', 'N2', 925, 2, 'academic'),
('標準的な', 'ひょうじゅんてきな', 'standard', 'Adjective', 'N2', 926, 3, 'academic'),
('特定の', 'とくていの', 'specific/particular', 'Adjective', 'N2', 927, 2, 'academic'),
('既存の', 'きぞんの', 'existing/current', 'Adjective', 'N2', 928, 3, 'business'),
('従来の', 'じゅうらいの', 'conventional/traditional', 'Adjective', 'N2', 929, 3, 'business'),
('今後', 'こんご', 'from now on', 'Noun', 'N2', 930, 2, 'business'),
('先行き', 'さきゆき', 'future prospects', 'Noun', 'N2', 931, 3, 'business'),
('背景にある', 'はいけいにある', 'to be in the background', 'Expression', 'N2', 932, 3, 'academic'),
('根本的な', 'こんぽんてきな', 'fundamental/basic', 'Adjective', 'N2', 933, 3, 'academic'),
('本質的な', 'ほんしつてきな', 'essential/fundamental', 'Adjective', 'N2', 934, 4, 'academic'),
('表面的な', 'ひょうめんてきな', 'superficial', 'Adjective', 'N2', 935, 3, 'academic'),
('形式的な', 'けいしきてきな', 'formal/superficial', 'Adjective', 'N2', 936, 3, 'business'),
('実質的な', 'じっしつてきな', 'substantial/real', 'Adjective', 'N2', 937, 3, 'business'),
('合理的な', 'ごうりてきな', 'rational/reasonable', 'Adjective', 'N2', 938, 3, 'academic'),
('論理的な', 'ろんりてきな', 'logical', 'Adjective', 'N2', 939, 3, 'academic'),
('感覚的な', 'かんかくてきな', 'intuitive/sensory', 'Adjective', 'N2', 940, 3, 'academic'),
('経験的な', 'けいけんてきな', 'empirical/experiential', 'Adjective', 'N2', 941, 4, 'academic'),
('科学的な', 'かがくてきな', 'scientific', 'Adjective', 'N2', 942, 2, 'academic'),
('技術的な', 'ぎじゅつてきな', 'technical', 'Adjective', 'N2', 943, 2, 'academic'),
('経済的な', 'けいざいてきな', 'economic/economical', 'Adjective', 'N2', 944, 2, 'business'),
('政治的な', 'せいじてきな', 'political', 'Adjective', 'N2', 945, 2, 'academic'),
('社会的な', 'しゃかいてきな', 'social', 'Adjective', 'N2', 946, 2, 'academic'),
('文化的な', 'ぶんかてきな', 'cultural', 'Adjective', 'N2', 947, 2, 'academic'),
('国際的な', 'こくさいてきな', 'international', 'Adjective', 'N2', 948, 2, 'academic'),
('人道的な', 'じんどうてきな', 'humanitarian', 'Adjective', 'N2', 949, 3, 'academic'),
('倫理的な', 'りんりてきな', 'ethical', 'Adjective', 'N2', 950, 3, 'academic');

INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('段取り', 'だんどり', 'arrangement/plan', 'Noun', 'N2', 951, 3, 'business'),
('見積もる', 'みつもる', 'to estimate', 'Verb', 'N2', 952, 2, 'business'),
('算出する', 'さんしゅつする', 'to calculate', 'Verb', 'N2', 953, 3, 'business'),
('割り当てる', 'わりあてる', 'to assign/allocate', 'Verb', 'N2', 954, 3, 'business'),
('振り分ける', 'ふりわける', 'to distribute/divide', 'Verb', 'N2', 955, 3, 'business'),
('取り組む', 'とりくむ', 'to tackle/work on', 'Verb', 'N2', 956, 2, 'business'),
('向き合う', 'むきあう', 'to face/deal with', 'Verb', 'N2', 957, 3, 'daily'),
('歩み寄る', 'あゆみよる', 'to make concessions', 'Verb', 'N2', 958, 3, 'business'),
('打開する', 'だかいする', 'to break through (deadlock)', 'Verb', 'N2', 959, 4, 'business'),
('模索する', 'もさくする', 'to grope for/search for', 'Verb', 'N2', 960, 4, 'academic'),
('試みる', 'こころみる', 'to try/attempt', 'Verb', 'N2', 961, 3, 'daily'),
('着手する', 'ちゃくしゅする', 'to start/begin', 'Verb', 'N2', 962, 3, 'business'),
('完了する', 'かんりょうする', 'to complete/finish', 'Verb', 'N2', 963, 2, 'business'),
('着実に', 'ちゃくじつに', 'steadily/surely', 'Adverb', 'N2', 964, 3, 'business'),
('速やかに', 'すみやかに', 'promptly/quickly', 'Adverb', 'N2', 965, 3, 'business'),
('適宜', 'てきぎ', 'appropriately/as needed', 'Adverb', 'N2', 966, 4, 'business'),
('逐次', 'ちくじ', 'one by one/sequentially', 'Adverb', 'N2', 967, 4, 'academic'),
('順次', 'じゅんじ', 'in order/sequentially', 'Adverb', 'N2', 968, 3, 'business'),
('随時', 'ずいじ', 'at any time/as occasion demands', 'Adverb', 'N2', 969, 3, 'business'),
('早急に', 'そうきゅうに', 'urgently/immediately', 'Adverb', 'N2', 970, 3, 'business'),
('優先的に', 'ゆうせんてきに', 'preferentially', 'Adverb', 'N2', 971, 3, 'business'),
('包括的に', 'ほうかつてきに', 'comprehensively', 'Adverb', 'N2', 972, 4, 'academic'),
('系統的に', 'けいとうてきに', 'systematically', 'Adverb', 'N2', 973, 4, 'academic'),
('継続的に', 'けいぞくてきに', 'continuously', 'Adverb', 'N2', 974, 3, 'business'),
('段階的に', 'だんかいてきに', 'step by step', 'Adverb', 'N2', 975, 3, 'business'),
('根本から', 'こんぽんから', 'from the root/fundamentally', 'Expression', 'N2', 976, 3, 'academic'),
('一から', 'いちから', 'from scratch', 'Expression', 'N2', 977, 2, 'daily'),
('全力を尽くす', 'ぜんりょくをつくす', 'to give one''s all', 'Expression', 'N2', 978, 3, 'daily'),
('力を合わせる', 'ちからをあわせる', 'to join forces/cooperate', 'Expression', 'N2', 979, 3, 'daily'),
('手を打つ', 'てをうつ', 'to take action/make a move', 'Expression', 'N2', 980, 3, 'business'),
('壁にぶつかる', 'かべにぶつかる', 'to hit a wall (face difficulty)', 'Expression', 'N2', 981, 3, 'daily'),
('壁を乗り越える', 'かべをのりこえる', 'to overcome obstacles', 'Expression', 'N2', 982, 3, 'daily'),
('一歩一歩', 'いっぽいっぽ', 'step by step', 'Expression', 'N2', 983, 2, 'daily'),
('着実な歩み', 'ちゃくじつなあゆみ', 'steady progress', 'Expression', 'N2', 984, 3, 'business'),
('前向きに', 'まえむきに', 'positively/constructively', 'Adverb', 'N2', 985, 2, 'daily'),
('前向きな姿勢', 'まえむきなしせい', 'positive attitude', 'Expression', 'N2', 986, 3, 'business'),
('柔軟な対応', 'じゅうなんなたいおう', 'flexible response', 'Expression', 'N2', 987, 3, 'business'),
('冷静な判断', 'れいせいなはんだん', 'calm judgment', 'Expression', 'N2', 988, 3, 'business'),
('迅速な対応', 'じんそくなたいおう', 'prompt response', 'Expression', 'N2', 989, 3, 'business'),
('的確な指示', 'てきかくなしじ', 'accurate instruction', 'Expression', 'N2', 990, 3, 'business'),
('奨学金', 'しょうがくきん', 'scholarship', 'Noun', 'N2', 991, 3, 'academic'),
('研究費', 'けんきゅうひ', 'research expenses', 'Noun', 'N2', 992, 3, 'academic'),
('申告書', 'しんこくしょ', 'declaration form', 'Noun', 'N2', 993, 3, 'business'),
('証明書類', 'しょうめいしょるい', 'supporting documents', 'Noun', 'N2', 994, 3, 'business'),
('在留資格', 'ざいりゅうしかく', 'residence status', 'Noun', 'N2', 995, 4, 'daily'),
('健康保険', 'けんこうほけん', 'health insurance', 'Noun', 'N2', 996, 2, 'daily'),
('年金', 'ねんきん', 'pension', 'Noun', 'N2', 997, 2, 'daily'),
('確定申告', 'かくていしんこく', 'tax return', 'Noun', 'N2', 998, 3, 'business'),
('消費税', 'しょうひぜい', 'consumption tax', 'Noun', 'N2', 999, 2, 'daily'),
('所得税', 'しょとくぜい', 'income tax', 'Noun', 'N2', 1000, 3, 'business');

-- Additional words to ensure 1000+ total
INSERT INTO vocabulary (kanji, furigana, english_meaning, part_of_speech, jlpt_level, frequency_rank, difficulty_level, category) VALUES
('公共', 'こうきょう', 'public', 'Noun', 'N2', 1001, 2, 'kanji'),
('民間', 'みんかん', 'private/civilian', 'Noun', 'N2', 1002, 2, 'kanji'),
('政府', 'せいふ', 'government', 'Noun', 'N2', 1003, 2, 'kanji'),
('行政', 'ぎょうせい', 'administration', 'Noun', 'N2', 1004, 3, 'kanji'),
('立法', 'りっぽう', 'legislation', 'Noun', 'N2', 1005, 3, 'kanji'),
('司法', 'しほう', 'judiciary', 'Noun', 'N2', 1006, 3, 'kanji'),
('議会', 'ぎかい', 'parliament/assembly', 'Noun', 'N2', 1007, 3, 'kanji'),
('選挙', 'せんきょ', 'election', 'Noun', 'N2', 1008, 2, 'kanji'),
('民主主義', 'みんしゅしゅぎ', 'democracy', 'Noun', 'N2', 1009, 3, 'academic'),
('人権', 'じんけん', 'human rights', 'Noun', 'N2', 1010, 3, 'academic'),
('憲法', 'けんぽう', 'constitution', 'Noun', 'N2', 1011, 3, 'academic'),
('条例', 'じょうれい', 'ordinance/bylaw', 'Noun', 'N2', 1012, 4, 'business'),
('規約', 'きやく', 'rules/regulations', 'Noun', 'N2', 1013, 3, 'business'),
('方針書', 'ほうしんしょ', 'policy document', 'Noun', 'N2', 1014, 3, 'business'),
('指針', 'ししん', 'guideline', 'Noun', 'N2', 1015, 3, 'business'),
('慣行', 'かんこう', 'custom/practice', 'Noun', 'N2', 1016, 3, 'business'),
('先例', 'せんれい', 'precedent', 'Noun', 'N2', 1017, 4, 'academic'),
('慣習', 'かんしゅう', 'custom/convention', 'Noun', 'N2', 1018, 3, 'kanji'),
('伝承', 'でんしょう', 'legend/tradition', 'Noun', 'N2', 1019, 4, 'kanji'),
('継承', 'けいしょう', 'succession/inheritance', 'Noun', 'N2', 1020, 4, 'kanji');
