spring.application.name=japanese-learn
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/japaneselearn
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.sql.init.mode=never
spring.jackson.serialization.fail-on-empty-beans=false
